COUNTRY_CODES = {
    'A': 'Australia',
    'As': 'Asia',
    'B': 'Brazil',
    'C': 'Canada',
    'Ch': 'China',
    'D': 'Netherlands (Dutch)',
    'E': 'Europe',
    'F': 'France',
    'G': 'Germany',
    'Gr': 'Greece',
    'HK': 'Hong Kong',
    'I': 'Italy',
    'J': 'Japan',
    'K': 'Korea',
    'Nl': 'Netherlands',
    'No': 'Norway',
    'R': 'Russia',
    'S': 'Spain',
    'Sw': 'Sweden',
    'U': 'United States',
    'UK': 'United Kingdom',
    'W': 'World',
    'Unl': 'Unlicensed',
    'PD': 'Public domain, free software and freeware',
    'Unk': 'Unknown country'
}